services:
#    acme_test.example:
#        class: TestBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    
    finderService:
        class: TestBundle\Controller\FinderServiceController
        arguments: ['@service_container']